### ISSUE TITLE
cython requires numpy

### ISSUE THREAD

**Issue by piyushrpt** [aivazis/config#1]
cython by default requires -I NUMPY_INCDIR as it builds interface to lists as well as numpy arrays. Numpy can be self discovered using "import numpy; numpy.get_include()" once the version of python has been finalized.

**Comment by aivazis** [comment]
Any idea what happens on machines that don’t have numpy installed? I don’t typically install numpy on my computers, yet somehow python seems to build extensions successfully. Is this consistent with what you know about the problem?

— Michael

**Comment by piyushrpt** [comment]
True. The use case is very specific to the way we are trying to build extensions. Support for  automatic translation from lists to numpy arrays - and vice versa automatically becomes available to the user when numpy support is turned on. Using numpy is optional, but the majority of users will use the numpy interface for anything that involves arrays or images.

**Comment by piyushrpt** [comment]
Agreed. This is not a relevant issue. In our cmake files, we explicitly add NUMPY_INCLUDE_DIR and dont force cython to use it all the time.

**Comment by aivazis** [comment]
We should take care of this in the local Make.mm. I’ll try to make it easier by adding numpy support to config. Stay tuned.

-- Michael
